update-ignore.d/01update-ignore: add support for mktemp
On system where tempname is not installed, check if we could use mktemp
instead.

If we are at it, add a warning if neither of them is available.

Signed-off-by: Miklos Vajna <vmiklos@frugalware.org>

diff --git a/update-ignore.d/01update-ignore b/update-ignore.d/01update-ignore
--- a/update-ignore.d/01update-ignore
+++ b/update-ignore.d/01update-ignore
@@ -126,7 +126,14 @@ if [ -e "$file" ]; then
 		exit 1
 	fi
 	realfile="$file"
-	file=$(tempfile)
+	if [ -n "`type -p tempfile`" ]; then
+		tempfile="tempfile"
+	elif [ -n "`type -p mktemp`" ]; then
+		tempfile="mktemp"
+	else
+		echo "etckeeper warning: can't find tempfile or mktemp" >&2
+	fi
+	file=$($tempfile)
 	(
 		skipping=
 		while read line; do
