* Add tests for /etc/.git not yet existing and avoid doing bad things.   Closes: #451185 * If /etc/.git doesn't exist, display a suggestion to run etckeeper-init.

diff --git a/post-apt.d/50git-commit b/post-apt.d/50git-commit
--- a/post-apt.d/50git-commit
+++ b/post-apt.d/50git-commit
@@ -1,9 +1,12 @@
 #!/bin/sh
 set -e
 
-# TODO: figure out what packages were acted on by the apt run, and include
-# that info in the commit message
-message="committing changes after apt run"
+if [ -d .git ]; then
 
-# ignore exit code since it exits nonzero if there is nothing to do
-git commit -m "$message" || true
+	# TODO: figure out what packages were acted on by the apt run, and
+	# include that info in the commit message
+	message="committing changes after apt run"
+
+	# ignore exit code since it exits nonzero if there is nothing to do
+	git commit -m "$message" || true
+fi
