ignore file update support
* etckeeper update-ignore will automatically update the VCS ignore
  file, only touching the part inside a "managed by etckeeper"
  comment block.
* Run etckeeper update-ignore on upgrade.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -72,4 +72,7 @@ configure)
 			fi
 		done
 	fi
+
+	# prints error and exits nonzero if the ignore file cannot be updated
+	etckeeper update-ignore || true
 esac
