uninit and auto-init
* Add uninit subcommand, which cleans up all etckeeper and VCS droppings
  in /etc. This is useful if you want to switch to a different VCS and
  don't have any history to preserve. (Preserving history and converting
  is of course possible, but significantly harder.)
* Run etckeeper init on initial install. Closes: #505772
  (The idea being that if someone doesn't want to use git, they can
  immediatly uninit to easily reverse this.)
* Document how to change the VCS used by etckeeper, without preserving
  any history. Preserving history left as an exersise for the reader.
  Closes: #515237

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -73,6 +73,12 @@ configure)
 		done
 	fi
 
+	if [ "$2" = "" ]; then
+		# Fresh install.
+		# Might fail if, eg, git is not installed.
+		etckeeper init || echo "etckeeper init failed; run it by hand" >&2
+	fi
+
 	# prints error and exits nonzero if the ignore file cannot be updated
 	etckeeper update-ignore || true
 esac
