Make etckeeper uninit -f disable the prompt.

diff --git a/uninit.d/01prompt b/uninit.d/01prompt
--- a/uninit.d/01prompt
+++ b/uninit.d/01prompt
@@ -1,18 +1,20 @@
 #!/bin/sh
 set -e
 
-echo "** Warning: This will DESTROY all recorded history for $ETCKEEPER_DIR,"
-echo "** including the $VCS repository and ignore file."
-echo ""
-printf "Are you sure you want to do this? [yN] "
-read answer
-case "$answer" in 
-	[Yy]*)
-		echo "Proceeding.."
-		exit 0
-	;;
-	*)
-		echo "Aborting etckeeper uninit."
-		exit 1
-	;;
-esac
+if [ "$1" != "-f" ]; then
+	echo "** Warning: This will DESTROY all recorded history for $ETCKEEPER_DIR,"
+	echo "** including the $VCS repository and ignore file."
+	echo ""
+	printf "Are you sure you want to do this? [yN] "
+	read answer
+	case "$answer" in 
+		[Yy]*)
+			echo "Proceeding.."
+			exit 0
+		;;
+		*)
+			echo "Aborting etckeeper uninit."
+			exit 1
+		;;
+	esac
+fi
