make message clearer

diff --git a/pre-install.d/50uncommitted-changes b/pre-install.d/50uncommitted-changes
--- a/pre-install.d/50uncommitted-changes
+++ b/pre-install.d/50uncommitted-changes
@@ -11,7 +11,10 @@ fi
 
 if etckeeper unclean; then
 	if [ "$AVOID_COMMIT_BEFORE_INSTALL" ]; then
-		echo "error: etckeeper detected uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run" >&2 
+		echo "" >&2
+		echo "** etckeeper detected uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run" >&2 
+		echo "** Aborting $HIGHLEVEL_PACKAGE_MANAGER run. Manually commit and restart." >&2
+		echo "" >&2
 		exit 1
 	fi
 	if ! etckeeper commit "saving uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run"; then
