Add a AVOID_COMMIT_BEFORE_INSTALL option in the config file to make it easy to configure etckeeper to abort an installation if there are uncommitted changes in /etc. Closes: #478754

diff --git a/pre-install.d/50uncommitted-changes b/pre-install.d/50uncommitted-changes
--- a/pre-install.d/50uncommitted-changes
+++ b/pre-install.d/50uncommitted-changes
@@ -10,6 +10,10 @@ if [ "$1" = "fail-debconf" ]; then
 fi
 
 if etckeeper unclean; then
+	if [ ! "$AVOID_COMMIT_BEFORE_INSTALL" ]; then
+		echo "error: etckeeper detected uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run" >&2 
+		exit 1
+	fi
 	if ! etckeeper commit "saving uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run"; then
 		if [ -e /usr/share/debconf/confmodule ]; then
 			$0 fail-debconf
