replace git-foo with git foo
from the release notes of the upcoming 1.5.4 release:

"The next feature release of git (this change is scheduled for v1.6.0) will by
default install dashed form of commands (e.g. "git-commit") outside of users'
normal $PATH"

diff --git a/init.d/70git-add b/init.d/70git-add
--- a/init.d/70git-add
+++ b/init.d/70git-add
@@ -1,5 +1,5 @@
 #!/bin/sh
 set -e
-if ! git-add .; then
-	echo "etckeeper warning: git-add failed" >&2
+if ! git add .; then
+	echo "etckeeper warning: git add failed" >&2
 fi
diff --git a/post-install.d/30git-add b/post-install.d/30git-add
--- a/post-install.d/30git-add
+++ b/post-install.d/30git-add
@@ -1,7 +1,7 @@
 #!/bin/sh
 set -e
 if [ -d .git ]; then
-	if ! git-add .; then
-		echo "etckeeper warning: git-add failed" >&2
+	if ! git add .; then
+		echo "etckeeper warning: git add failed" >&2
 	fi
 fi
