* Add support for bzr, thanks to Mark A. Hershberger. Closes: #470515   (Note that bzr does not support etckeeper's pre-commit hook.)

diff --git a/init.d/70vcs-add b/init.d/70vcs-add
--- a/init.d/70vcs-add
+++ b/init.d/70vcs-add
@@ -9,4 +9,8 @@ elif [ "$VCS" = hg ]; then
 	if ! hg add .; then
 		echo "etckeeper warning: hg add failed" >&2
 	fi
+elif [ "$VCS" = bzr ]; then
+	if ! bzr add .; then
+		echo "etckeeper warning: bzr add failed" >&2
+	fi
 fi
