Tranlsation of init.d in mercurial idiom

diff --git a/hg/init.d/70hg-add b/hg/init.d/70hg-add
--- a/hg/init.d/70hg-add
+++ b/hg/init.d/70hg-add
@@ -1,5 +1,5 @@
 #!/bin/sh
 set -e
-if ! git-add .; then
-	echo "etckeeper warning: git-add failed" >&2
+if ! hg addremove .; then
+	echo "etckeeper warning: hg addremove failed" >&2
 fi
